server:
  port: 20080
  servlet:
    context-path: /api
spring:
  datasource:
    schema1:
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: HikariPoolGenesis
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:23306/schema1?useUnicode=true&characterEncoding=UTF-8
      username: app_user
      password: app_user_password
      auto-commit: false
      connection-timeout: 5000
      minimum-idle: 1
      maximum-pool-size: 10
      connection-test-query: SELECT 1 FROM DUAL
